/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface USpinner {}
  interface UStockFinder {}
  interface UStockPrice {
    'stockSymbol': string;
  }
}

declare global {


  interface HTMLUSpinnerElement extends Components.USpinner, HTMLStencilElement {}
  var HTMLUSpinnerElement: {
    prototype: HTMLUSpinnerElement;
    new (): HTMLUSpinnerElement;
  };

  interface HTMLUStockFinderElement extends Components.UStockFinder, HTMLStencilElement {}
  var HTMLUStockFinderElement: {
    prototype: HTMLUStockFinderElement;
    new (): HTMLUStockFinderElement;
  };

  interface HTMLUStockPriceElement extends Components.UStockPrice, HTMLStencilElement {}
  var HTMLUStockPriceElement: {
    prototype: HTMLUStockPriceElement;
    new (): HTMLUStockPriceElement;
  };
  interface HTMLElementTagNameMap {
    'u-spinner': HTMLUSpinnerElement;
    'u-stock-finder': HTMLUStockFinderElement;
    'u-stock-price': HTMLUStockPriceElement;
  }
}

declare namespace LocalJSX {
  interface USpinner {}
  interface UStockFinder {
    'onUSymbolSelected'?: (event: CustomEvent<string>) => void;
  }
  interface UStockPrice {
    'stockSymbol'?: string;
  }

  interface IntrinsicElements {
    'u-spinner': USpinner;
    'u-stock-finder': UStockFinder;
    'u-stock-price': UStockPrice;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'u-spinner': LocalJSX.USpinner & JSXBase.HTMLAttributes<HTMLUSpinnerElement>;
      'u-stock-finder': LocalJSX.UStockFinder & JSXBase.HTMLAttributes<HTMLUStockFinderElement>;
      'u-stock-price': LocalJSX.UStockPrice & JSXBase.HTMLAttributes<HTMLUStockPriceElement>;
    }
  }
}


