/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UStockPrice {}
}

declare global {


  interface HTMLUStockPriceElement extends Components.UStockPrice, HTMLStencilElement {}
  var HTMLUStockPriceElement: {
    prototype: HTMLUStockPriceElement;
    new (): HTMLUStockPriceElement;
  };
  interface HTMLElementTagNameMap {
    'u-stock-price': HTMLUStockPriceElement;
  }
}

declare namespace LocalJSX {
  interface UStockPrice {}

  interface IntrinsicElements {
    'u-stock-price': UStockPrice;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'u-stock-price': LocalJSX.UStockPrice & JSXBase.HTMLAttributes<HTMLUStockPriceElement>;
    }
  }
}


